### ISSUE TITLE
New Recording Feature issue + Transparent Overlay Background

### ISSUE THREAD

**Issue by isdorito** [SaiyajinK/Minimal-Dark-for-Steam#11]
The new Recording Feature that is on the beta branch makes all the windows invisible.
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/84813812/e698d5d8-b722-4c3b-b188-1c74f710072a)

And i also need a little help here. I would like to make the background transparent when using the in-game overlay. Could you lend me a hand with that?

**Comment by SaiyajinK** [comment]
Yeah, I fixed this and took the opportunity to adapt the new functionality to the skin:

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/edbaa461-97a5-4790-91fa-aab7b9d63f0a)

Since I don't have much time at the moment, I will finalize the remaining interface details later.

update the skin to [2.9.9](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/releases/tag/2.9.9)  👍🏻
