### ISSUE TITLE
[BUG] Overlay notes collapse button not working 

### ISSUE THREAD

**Issue by OsuCelsius** [SaiyajinK/Minimal-Dark-for-Steam#15]
![image](https://github.com/user-attachments/assets/21eca408-42aa-4673-93ec-ef0d8104be83)

**Comment by SaiyajinK** [comment]
You are on the beta channel, but I noticed and reproduced the bug on the stable channel, I updated the skin to [3.0.4](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/releases/tag/3.0.4), the fix is ​​included (button & beta ui).

![BattleBit_YieWQ9FnCB](https://github.com/user-attachments/assets/99f03c1a-ec1a-472a-b10c-f5354944aa0c)

for maximum compatibility, I advise you to switch to the stable channel.

**Comment by OsuCelsius** [comment]
It's not fixed, with every other skin it works fine, only this one failes
