### ISSUE TITLE
[QUESTION] How to get the default profile page in newer versions

### ISSUE THREAD

**Issue by OsuCelsius** [SaiyajinK/Minimal-Dark-for-Steam#16]
I want to have the default profile page colors, in the previous version you have to comment this lines
```
/*
 background profil video/wallpaper remove static color 
.profile_animated_background > video {
    display: none !important;
}

div.profile_page.has_profile_background {
    background: var(--minimal_dark_blacker_alt) !important;
    background-image: none !important;
} 
*/

.profile_animated_background {
    background-color: #000000 !important; /* set var(--minimal_dark_blacker_alt) if you have remove the lines above */
}
/* end background profil video/wallpaper remove static color */
```

How can I do that in the newer version?

**Comment by SaiyajinK** [comment]
You won't be able to do this (unless you modify it yourself) because I changed the design a few weeks ago and as I said on another issue, I can't provide a custom skin for every request. After several feedbacks, I decided to "mix" the minimal (remove all static colors) and the basic theme, that's why the option you asked for is no longer available, and in itself, there are not many differences.

vanilla:
![vanilla](https://github.com/user-attachments/assets/5579df9b-ee9f-4475-9d29-ca82713127d1)


minimal:
![minimalw](https://github.com/user-attachments/assets/f610c652-4fd0-4f4e-900c-59f330ba59ba)

nothing prevents you from using another webkit but compatibility with Minimal will be non-existent.
