### ISSUE TITLE
Small visual overlap with the new account button.

### ISSUE THREAD

**Issue by Mariobruh64** [SaiyajinK/Minimal-Dark-for-Steam#23]
Small visual difference with the VR icon with the new account button change. If too minor just close this report, as it isn't that much of a bother, more of a heads up.
![Screenshot 2024-09-27 165730](https://github.com/user-attachments/assets/d6e831d6-99ed-4644-b108-46dd6854947c)

**Comment by SaiyajinK** [comment]
Yes i see that. No worries when the problem is simple to fix (and if it worked well before) you should not hesitate to report it.

I made the necessary adjustments, let me know if it's good on your side (update the skin) 👍🏻 

![image](https://github.com/user-attachments/assets/5c5245d2-1b84-4d41-acc4-fe0c7b894c31)

**Comment by SaiyajinK** [comment]
Yes i see that. No worries when the problem is simple to fix (or not, and if it worked well before) you should not hesitate to report it.

I made the necessary adjustments, let me know if it's good on your side (update the skin) 👍🏻 

![image](https://github.com/user-attachments/assets/5c5245d2-1b84-4d41-acc4-fe0c7b894c31)

**Comment by Mariobruh64** [comment]
Fix works, thanks again!
