### ISSUE TITLE
Webkit. steam wishlist

### ISSUE THREAD

**Issue by madmaxgrey** [SaiyajinK/Minimal-Dark-for-Steam#27]
wishlist section isn't themed
![image](https://github.com/user-attachments/assets/c332f1fb-40fa-421f-b444-fa5e383fa396)

**Comment by madmaxgrey** [comment]
the background area where its blue

**Comment by SaiyajinK** [comment]
Yes, it's been 2 months since an update replaced the skin's background with blue.

![image](https://github.com/user-attachments/assets/13708ec6-679c-46fb-9753-1e0bfb662895)

As you can see in the screenshot just above, the code is present in Minimal's webkit.css file, but a Steam employee had the brilliant idea of ​​putting the !important; tag directly on the source, which makes any external modifications impossible (at least not to my knowledge).

**Comment by SaiyajinK** [comment]
Yes, it's been 2 months since an update replaced the skin's background with blue, but I didn't think about it anymore.

![image](https://github.com/user-attachments/assets/13708ec6-679c-46fb-9753-1e0bfb662895)

As you can see in the screenshot just above, the code is present in Minimal's webkit.css file, but a Steam employee had the brilliant idea of ​​putting the `!important;` tag directly on the source, which makes any external modifications delicate. 

I posted an update for fix this, it should be fine now. 👍🏻

**Comment by madmaxgrey** [comment]
thank you :)
