### ISSUE TITLE
User profiles background does not show anymore

### ISSUE THREAD

**Issue by CatPieLeaf** [SaiyajinK/Minimal-Dark-for-Steam#3]
The animated and static background of user profiles (full profiles, not mini profiles) are entirely black. on previous releases, the backgrounds were appearing.
the same happens to game page backgrounds. 

this is probably due to an update on webkit.css

**Comment by SaiyajinK** [comment]
Hi, 

Yes this changed in a previous update for the profile.
It is stated in the description :

> I defined a static color by default which will have the effect of not displaying static or video backgrounds.
> If you want to remove this, open `webkit.css` and remove lines `98` to `106` and edit line `109`

(make sure you have the latest version)

and regarding the games page yes too, but on this point I will have to look more closely when I have a little more time because the static color affects a lot of elements and removing it breaks a lot of parts of the webkit without having to modify everything again. It's not my priority at the moment.

Just know that if you wish you can use another webkit from another theme but I in no way guarantee compatibility with Minimal Dark.

Another solution, you can fiddle with yourself with the devtool to adapt according to your needs but just remember that each millennium update (whether manual from the settings or automatic at startup or configured from steam) will cancel all your changes because your modified files will be overwritten by Millennium to put back those present in the github directory.
