### ISSUE TITLE
Bug - Friend Tooltip not overflowing properly

### ISSUE THREAD

**Issue by littlepriceonu** [SaiyajinK/Minimal-Dark-for-Steam#9]
When you go to a game in your library and hover over a friend in the "Friends Who Play" section, if they have a award displayed on their profile, the tooltip will overflow incorrectly and the playtime wont be visible.

Examples: 

![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/63677850/73b44d48-4437-4611-be18-2004ff6360cf)
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/63677850/f93b8c43-d213-4fa1-bcaf-2cba3e9d0a9f)

**Comment by SaiyajinK** [comment]
Yes indeed, this must have happened because I recently changed the friends list.

I updated the skin to [2.9.8](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/releases/tag/2.9.8) and it includes the fix.

without award badge :
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/b50cb08e-1b00-4e85-8a07-f9c9311ec349)

with award badge:
![image](https://github.com/SaiyajinK/Minimal-Dark-for-Steam/assets/105972098/352117c5-446b-4c57-87d6-50605b88728b)

Let me know if everything is fine on your end after the update.

**Comment by SaiyajinK** [comment]
No news, good news. I'm closing the issue.
